### PR TITLE
Fix reading double from a string on aarch64

### PR DESCRIPTION
**Pull request by eukarpov**
CI test passed
https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/actions/runs/7115452148

### CODE REVIEW

**Review by ZacWalk — COMMENTED** [review]
I dont know why changing __mingw_strtold  to strtold fixes this. Could you explain why this is the fix? I know there were some changes related to __mingw_strtold  being renamed in another PR.

**Comment by eukarpov** [comment]
> I dont know why changing __mingw_strtold to strtold fixes this. Could you explain why this is the fix? I know there were some changes related to __mingw_strtold being renamed in another PR.

The change has been introduced here to support strtold on aarch64, however sscanf has not been fixed 
https://github.com/Windows-on-ARM-Experiments/mingw-woarm64/blob/5ddbab035ff91766436c3422f4e0a85fbc1ca5d8/mingw-w64-crt/gdtoa/strtopx.c#L137

**Comment by eukarpov** [comment]
I think alternatively it can be also fixed by extending condition for aarch64 here 
https://github.com/Windows-on-ARM-Experiments/mingw-woarm64/blob/5ddbab035ff91766436c3422f4e0a85fbc1ca5d8/mingw-w64-crt/gdtoa/strtodnrp.c#L88

**Comment by Blackhex** [comment]
> I think alternatively it can be also fixed by extending condition for aarch64 here
> 
> https://github.com/Windows-on-ARM-Experiments/mingw-woarm64/blob/5ddbab035ff91766436c3422f4e0a85fbc1ca5d8/mingw-w64-crt/gdtoa/strtodnrp.c#L88

If `long double` == `double` on aarch64, this fix would be more appropriate as the coment of the condition suggests.

**Comment by ZacWalk** [comment]
I then see in libgfortran.h and scanf the change to **not** use __strtold (or __mingw_strtold) for __aarch64__ and instead use strtold. I assume above change is because in mingw __strtold is defined (with two aliases __mingw_strtold,  strtold) only for x64 and not for aarch64.

My recommendation would be to just create aliases for __mingw_strtold and __strtold for the __aarch64__ case in strtopx.c. Have them point to strtold. That way no changes would be needed in libfortran or scanf.

However, in out toolchain 'long double' and double are not equivalent. One is 16 bytes the other is 8 bytes. This means there is a missing implementation of strtold for 16 byte doubles in mingw. But I guess that can be done later.

**Comment by eukarpov** [comment]
> I then see in libgfortran.h and scanf the change to **not** use __strtold (or __mingw_strtold) for **aarch64** and instead use strtold. I assume above change is because in mingw __strtold is defined (with two aliases __mingw_strtold, strtold) only for x64 and not for aarch64.
> 
> My recommendation would be to just create aliases for __mingw_strtold and __strtold for the **aarch64** case in strtopx.c. Have them point to strtold. That way no changes would be needed in libfortran or scanf.
> 
> However, in out toolchain 'long double' and double are not equivalent. One is 16 bytes the other is 8 bytes. This means there is a missing implementation of strtold for 16 byte doubles in mingw. But I guess that can be done later.

It was already done in libgfortran.h to support aarch64 changes in mingw for strtold
https://github.com/Windows-on-ARM-Experiments/gcc-woarm64/pull/10

**Comment by ZacWalk** [comment]
> It was already done in libgfortran.h to support aarch64 changes in mingw for strtold [Windows-on-ARM-Experiments/gcc-woarm64#10](https://github.com/Windows-on-ARM-Experiments/gcc-woarm64/pull/10)

That is what I mean. That fix and this fix are both treating the symptom of missing aliases.

**Comment by eukarpov** [comment]
> Here is more information why it was done this way
> https://github.com/Windows-on-ARM-Experiments/mingw-woarm64/commit/54bbe83dfe0a134558bcd85663a4a8b2ff1bc063

Sorry, I don’t see why that is related to missing aliases for __mingw_strtold and __strtold in aarch64. Could you explain a little?

**Comment by eukarpov** [comment]
After all, it looks like alias cannot be used due to functions have different return type long double and double.
A direct call solves the problem and test pass

**Review by ZacWalk — APPROVED** [review]
LGTM

**Pull request merged**
